### ISSUE TITLE
Add an option to accept insecure URLs

### ISSUE THREAD

**Issue by toschder** [simplaex/waitfor-maven-plugin#8]
The service I´m currently testing is using a certificate which is not globally trusted. 
That´s why I´m getting:
`[INFO] >>> Checking https://localhost:8181/myservice/actuator/health...
[INFO]
[WARNING] https://localhost:8181/myservice/actuator/health failed (javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target)
[INFO]
[INFO] >>> Not all checks passed. Trying again...
`

With curl it would be just a "-k" or "--insecure" option. 

Can you add this option here, too, so https URL will be accepted (with a warning in the output) - instead of failing ?

Thx!

**Comment by scravy** [comment]
I believe you should be able to accomplish this by using various command line arguments to the JVM, see https://stackoverflow.com/questions/4663147/is-there-a-java-setting-for-disabling-certificate-validation

That thread also mentions how to do it programmatically, you are more than welcome to send a pull request for this :-)

**Comment by dadoonet** [comment]
I created #10 which I hope could help.
